### ISSUE TITLE
Provide wheel distribution on PyPI

### ISSUE THREAD

**Issue by edmorley** [kumar303/mohawk#14]
Please could you provide a wheel archive on PyPI alongside the standard package? http://pythonwheels.com/

Many thanks :-)

**Comment by edmorley** [comment]
When you release 0.3.3, could you remember the wheel? (It was forgotten for 0.3.1, 0.3.2 and 0.3.2.1)

Thanks :-)

**Comment by kumar303** [comment]
Done. Thanks for help on the docs. https://pypi.python.org/pypi/mohawk
