### ISSUE TITLE
PyPI package includes the mohawk tests

### ISSUE THREAD

**Issue by edmorley** [kumar303/mohawk#18]
Not urgent at all, but the package on PyPI includes `mohawk/tests.py`, presumably since setuptools is just collecting everything in the mohawk directory. It accounts for 20KB out of the uncompressed package size of 54KB.

Would `tests/tests.py` be a better location? :-)

**Comment by kumar303** [comment]
I sort of like to distribute tests in the package. That way someone could verify a distributed package if they wanted to. If it were a JavaScript module where small package size is crucial I'd be more concerned about the space. In any case, I don't feel strongly about it so if you'd rather remove tests from the distribution I'd accept a patch for it.

**Comment by edmorley** [comment]
Makes sense - doesn't bother me too much, just wanted to make sure it was intentional :-)
