### ISSUE TITLE
Add expiration to bewits

### ISSUE THREAD

**Issue by jhford** [kumar303/mohawk#19]
We'd love to move to mohawk for the taskcluster python client library.  It's great that bewits have been added, but we need to have expiration support.  Is it possible to have expiring bewits?

**Comment by kumar303** [comment]
For now you can make a bewit expire by setting [resource.timestamp](https://github.com/kumar303/mohawk/blob/master/mohawk/bewit.py#L62) to your future expiration time.

I know this is a little awkward; there will be a better way to do it after https://github.com/kumar303/mohawk/issues/17
