### ISSUE TITLE
Handle non-string 'Authorization' header more gracefully

### ISSUE THREAD

**Issue by edmorley** [kumar303/mohawk#23]
I'm adding mohawk to a legacy web.py project, and was performing the http auth header lookup like so:

``` python
auth_header = web.ctx.environ.get('HTTP_AUTHORIZATION')
...
Receiver(lookup_hawk_credentials,
         auth_header,
         url,
         ...)
```

However if the auth header isn't present, this results in a value of `None` being passed to the Receiver constructor, which results in:

```
  File "/home/Ed/.virtualenvs/of/lib/python2.7/site-packages/mohawk/receiver.py", line 82, in __init__
    parsed_header = parse_authorization_header(request_header)
  File "/home/Ed/.virtualenvs/of/lib/python2.7/site-packages/mohawk/util.py", line 158, in parse_authorization_header
    parts = auth_header.split(',')
AttributeError: 'NoneType' object has no attribute 'split'
```

Whilst the API docs do state that the auth header should be a string:
http://mohawk.readthedocs.org/en/latest/api.html#receiver

...they say the same for the others that default to `None`, so it's easy to think that a `None`-value will be handled.

Instead perhaps it should raise either a generic `HawkFail` (like happens if the header doesn't start with 'hawk': [link](https://github.com/kumar303/mohawk/blob/0.3.1/mohawk/util.py#L160-L162)) or else a new exception for missing header?
http://mohawk.readthedocs.org/en/latest/api.html#exceptions

(Using mohawk 0.3.1)

**Comment by kumar303** [comment]
yes, this is a bug. It should definitely raise a HawkFail derivative so a proper 403 response can be returned.

**Comment by kumar303** [comment]
Thanks for the patch @thusoy ! I pushed 0.3.4 to PyPI with this change.

* http://mohawk.readthedocs.io/en/latest/#changelog
* https://pypi.python.org/pypi/mohawk

**Comment by thusoy** [comment]
Great, thanks for the quick response! 

On January 7, 2017 9:42:21 PM GMT+01:00, Kumar McMillan <notifications@github.com> wrote:
>Thanks for the patch @thusoy ! I pushed 0.3.4 to PyPI with this change.
>
>* http://mohawk.readthedocs.io/en/latest/#changelog
>* https://pypi.python.org/pypi/mohawk
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/kumar303/mohawk/issues/23#issuecomment-271108837

-- 
Have a splendid day! 

Sent from phone, thus potentially short.

Tarjei
