### ISSUE TITLE
Update publishing a release docs with wheel instructions

### ISSUE THREAD

**Issue by edmorley** [kumar303/mohawk#30]
The docs here:
https://mohawk.readthedocs.io/en/latest/developers.html#publish-a-release

Could do with the changes that landed in hawkrest:
https://hawkrest.readthedocs.io/en/latest/developers.html#publish-a-release

**Comment by kumar303** [comment]
Good idea. I guess that slipped through the cracks.

**Comment by edmorley** [comment]
Thanks :-)

**Comment by kumar303** [comment]
0.3.3 is available now https://pypi.python.org/pypi/mohawk
