### ISSUE TITLE
re.LOCALE with str pattern deprecated on python 3.5

### ISSUE THREAD

**Issue by thusoy** [kumar303/mohawk#32]
Importing mohawk with warnings turned into exceptions exposes a deprecation warning:

```
tests/test_upload.py:5: in <module>
    from mohawk import Sender
venv/lib/python3.5/site-packages/mohawk/__init__.py:1: in <module>
    from .sender import *
venv/lib/python3.5/site-packages/mohawk/sender.py:3: in <module>
    from .base import default_ts_skew_in_seconds, HawkAuthority, Resource
venv/lib/python3.5/site-packages/mohawk/base.py:12: in <module>
    from .util import (calculate_mac,
venv/lib/python3.5/site-packages/mohawk/util.py:228: in <module>
    re.LOCALE)
venv/lib/python3.5/re.py:224: in compile
    return _compile(pattern, flags)
venv/lib/python3.5/re.py:293: in _compile
    p = sre_compile.compile(pattern, flags)
venv/lib/python3.5/sre_compile.py:536: in compile
    p = sre_parse.parse(p, flags)
venv/lib/python3.5/sre_parse.py:830: in parse
    p.pattern.flags = fix_flags(str, p.pattern.flags)
venv/lib/python3.5/sre_parse.py:804: in fix_flags
    DeprecationWarning, stacklevel=6)
E   DeprecationWarning: LOCALE flag with a str pattern is deprecated. Will be an error in 3.6
```

I don't see why header verification should be dependent on the locale, I'm assuming the `\w` can be replaced by a `a-zA-Z0-9` pattern to avoid any ambiguity, and the re.LOCALE flag removed?

**Comment by kumar303** [comment]
The intention was to only allow ascii words in the header. I'm actually not sure why the [LOCALE flag](https://docs.python.org/2/library/re.html#re.LOCALE) was used for this, maybe it worked by side effect? 

It looks like there is a new [ASCII flag](https://docs.python.org/3/library/re.html#re.ASCII) we can use. However, I'm not sure how to make that backwards compatible with Python 2.x. Maybe [six](https://pythonhosted.org/six/) has a helper for it? Or maybe we don't care because `LOCALE` was hacky anyway?

**Comment by thusoy** [comment]
The comment above the line in question defines all the accepted characters in the header anyway, and without doing a very careful read of the regex it looks like the only difference is that a-zA-Z0-9 has been replaced by `\w`, so I think you can just use that directly and then all accepted characters will be well defined (ascii words, in practice).

**Comment by kumar303** [comment]
wouldn't `é` or `å` be caught in `a-z`? I haven't tried but I'm not sure what would happen.

**Comment by thusoy** [comment]
No, a-z is what you'd expect, just the letters from a to z. But that's just a small test away if you want to verify it.

On August 17, 2016 7:48:26 AM PDT, Kumar McMillan <notifications@github.com> wrote:
>wouldn't `é` or `å` be caught in `a-z`? I haven't tried but I'm not
>sure what would happen.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/kumar303/mohawk/issues/32#issuecomment-240435877

-- 
Have a splendid day! 

Sent from phone, thus potentially short.

Tarjei

**Comment by kumar303** [comment]
> No, a-z is what you'd expect, just the letters from a to z.

`é` is a letter between a-z so I'm not sure what to expect :) Yes, before switching to regex this needs to be tested. Adding these tests to the suite sounds like a good idea too.

**Comment by thusoy** [comment]
I meant in the ASCII way: http://www.asciitable.com/

But you can just check it: 
```
python -c "import re; print(re.match('[a-z]', 'é'))"
None
python -c "import re; print(re.match('[a-z]', 'e'))"
<_sre.SRE_Match object; span=(0, 1), match='e'>
```

**Comment by kumar303** [comment]
huh, ok, sounds good. I thought `$LANG` or `$LC_ALL` vars might have an effect but I guess not. That seems like a good fix then.

**Comment by thusoy** [comment]
Added a PR. Didn't add any new tests since there already were a couple testing for bad header values.
