### ISSUE TITLE
Commas in header values break parsing

### ISSUE THREAD

**Issue by thusoy** [kumar303/mohawk#34]
The parser tries to split the entire header `Hawk id="something", key="value"` on commas to separate the fields, thus any field with comma in it will cause breakage.

``` python
def test_ext_with_all_valid_characters(self):
    valid_characters = "!#$%&'()*+,-./:;<=>?@[]^_`{|}~ azAZ09"
    sender = self.Sender(ext=valid_characters)
    self.receive(sender.request_header)
    parsed = parse_authorization_header(sender.request_header)
    eq_(parsed['ext'], valid_characters)
```

Discovered when working on #33

**Comment by kumar303** [comment]
D'oh. Looks like the Node lib does not suffer from this: https://github.com/hueniverse/hawk/blob/master/lib/utils.js#L147
