### ISSUE TITLE
Deprecate and rename the always_hash_content=False keyword

### ISSUE THREAD

**Issue by kumar303** [kumar303/mohawk#40]
This is just a minor detail but the following keyword arg:
````py
sender = Sender(..., always_hash_content=False)
````
should be renamed to:
````py
sender = Sender(..., always_sign_content=False)
````
because the "hash" is just an artifact of signing the content. We can deprecate the old keyword arg and still support it.

Details: http://mohawk.readthedocs.io/en/latest/usage.html#skipping-content-checks

**Comment by kumar303** [comment]
Oh, we should probably also rename this one too, from:
````py
receiver = Receiver(..., accept_untrusted_content=True)
````
...to:
````py
receiver = Receiver(..., accept_unsigned_content=True)
````

**Comment by thusoy** [comment]
Technically there are no signatures involved in Hawk, only MACs. Signatures use asymmetric crypto. But `accept_unmacced_content` doesn't sound good either, so I don't think untrusted is too bad. Could also be unverified? Unprotected maybe?

**Comment by kumar303** [comment]
@rneilson could you file a new issue with the new option names you are proposing? As pointed out, it's inaccurate to say `always_sign_content` since that's the mac part, not the hash part. I was confused when I wrote up this issue!

**Comment by rneilson** [comment]
@kumar303 Will do. Should we close this one, then?

**Comment by kumar303** [comment]
Yes, I was going to wait for the other issue but it doesn't matter since this one is just confusing now :) Let's add a link here to the new issue in case someone digs it up by following a different thread.

**Comment by rneilson** [comment]
Continued in #46.
