### ISSUE TITLE
Remove support for escape characters in bewit `ext`

### ISSUE THREAD

**Issue by kumar303** [kumar303/mohawk#41]
In order to [fix header parsing](https://github.com/kumar303/mohawk/issues/34) the `ext` value can no longer contain escape characters. However, this limitation was not imposed on `ext` values used by [bewit](https://github.com/kumar303/mohawk/blob/master/mohawk/bewit.py) (AKA signed URLs). Let's put the same limitations on `ext` values used by the bewit function.

**Comment by thusoy** [comment]
I think this can be closed now, we handled bewits when refactoring header parsing.

**Comment by kumar303** [comment]
Yes, thanks for allowing me to scope creep your PR :) Fixed in https://github.com/kumar303/mohawk/pull/36
